openapi: 3.0.0
info:
  title: Coffee Maker API
  description: A very simple coffee maker API, for demonstrating code generation using OpenAPI
  version: "1.0.0"
tags:
  - name: Coffee Maker API
    description: Version 1 of the API
paths:
  /api/status:
    $ref: './paths/status.yaml#/coffee-maker-status'
  /api/orders:
    $ref: './paths/orders.yaml#/orders'
  #/api/v1/orders-duplicate:  # having two path pointing the same path item group is causing issues
  #  $ref: './paths/orders.yaml#/orders'
  /api/orders/{orderId}:
    $ref: './paths/orders.yaml#/order-by-id'
components:
  securitySchemes:
    customAuthentication:
      type: http
      scheme: bearer
      bearerFormat: jwt
